apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-skaffold-helm-deploy
    app.kubernetes.io/managed-by: Helm
  name: springboot-skaffold-helm-deploy
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-skaffold-helm-deploy
